### ISSUE TITLE
通过本地api方式注册和调用服务的方法

### ISSUE THREAD

**Issue by feelanture** [apache/incubator-servicecomb-java-chassis#132]
您好，根据项目需要，需要通过本地api方式注册和调用服务，请问，有相应的api接口和使用说明吗？谢谢！

**Comment by liubao68** [comment]
https://github.com/ServiceComb/service-center/tree/master/docs

**Comment by feelanture** [comment]
我根据服务注册参考的rest接口，其中的java的demo，页面描述如下：
import io.swagger.client.*;
import io.swagger.client.auth.*;
import io.swagger.client.model.*;
import .InstancesApi;

import java.io.File;
import java.util.*;

public class InstancesApiExample {

    public static void main(String[] args) {
        
        InstancesApi apiInstance = new InstancesApi();
        String serviceId = serviceId_example; // String | 微服务唯一标识。
        CreateInstance instance = ; // CreateInstance | 微服务实例请求结构体。
        try {
            CreateInstanceResponse result = apiInstance.register(serviceId, instance);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling InstancesApi#register");
            e.printStackTrace();
        }
    }
}

我把代码贴到本地，发现导入的类都不认识，请问，这个服务注册例子，是仅供说明使用，还是实在可以参考使用的？如果是，需要引用那些特殊的jar包。
rest风格的服务注册，是构建字符串然后发送http请求吗，还是需要使用api，需要有授权等环节？

**Comment by liubao68** [comment]
@feelanture 你的代码的来源是什么地方？ ServiceComb没找到对应的示例，也没有这些API。

**Comment by lijasonvip** [comment]
@feelanture, thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!

**Comment by zhengyangyong** [comment]
Hi @feelanture  , if you had any question, please contact us again, thanks!
