### ISSUE TITLE
关于服务端和客户提供异步调用的能力

### ISSUE THREAD

**Issue by wood001** [apache/incubator-servicecomb-java-chassis#155]
请问下ServiceComb有计划提供异步接口能力吗？下面是我的问题，以及我做了一些验证。

## 背景
 异步调用在高性能要求的场景下是必须的。

## 服务端的异步场景
  当前ServiceComb的服务端io和work是分离的，理论上可以通过调大work线程的个数来提高并发和吞吐，但是线程数目肯定不能太大。如果微服务内部又级联调用其他微服务或者数据库操作，并发量会受限。
  所以主流的rpc或者微服务框架都具备实现异步服务端的能力。
## 实现
  考虑到基于ServiceComb可以定义Pojo接口，并且定义的接口也会生成契约文件，所以尽量在接口定义中不引入其他开源的代码，Java的CompletableFuture是一个很好的桥接器。例如如下代码
```` Java
@RequestMapping(path = "/springmvchello", produces = MediaType.APPLICATION_JSON)
public class SpringmvcHelloImpl implements Hello {
  @RequestMapping(path = "/sayhello", method = RequestMethod.POST)
  public String sayHello(@RequestBody String person) {
    .........
  }
}
````
```` yaml
  /sayhello:
     post:
          operationId: sayHello
          parameters:
            - name: person
              in: body
              required: true
              type: string
          responses:
            200:
              description: 正确返回
              schema:
                type: string
````
可以支持契约文件不修改，然后服务接口修改成
```` Java
@RequestMapping(path = "/springmvchello", produces = MediaType.APPLICATION_JSON)
public class SpringmvcHelloImpl implements Hello {
  @RequestMapping(path = "/sayhello", method = RequestMethod.POST)
  public CompletableFuture<String> sayHello(@RequestBody String person) {
    CompletableFuture<String> result = new CompletableFuture<String>();
    .......
   return result;
  }
}
````

基于如上想法我已经大概修改了下代码并验证，希望ServiceComb近期版本能够提供异步能力。

**Comment by WillemJiang** [comment]
@wood001 感谢对异步支持的关注， ServiceComb JavaChassis对异步支持也有相关的规划。 
 从框架内部我们也有异步的调用接口， 现在需要在应用层面提供相关的处理接口。 从你的描述来看CompletableFuture 在应用层面提供了异步接口，我的感觉是这是给同步调用转异步提供了一个转接的方式， 不清楚你说的修改代码并验证的内容是哪些？可否提一个PR上来看看。

**Comment by wood001** [comment]
@WillemJiang 是的，ServiceComb内部的io和worker是分离的。我考虑的应用层和ServiceComb之间的异步，周末我来提交个push。

**Comment by lijasonvip** [comment]
@wood001, thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!

**Comment by zhengyangyong** [comment]
We had added `CompletableFuture`
