### ISSUE TITLE
是否存在根据schemaId查询所在微服务（微服务名）的接口

### ISSUE THREAD

**Issue by feelanture** [apache/incubator-servicecomb-java-chassis#190]
由于项目需要，需要在调用服务的时候，确定schemaId所在微服务的位置，而不用开发人员传入微服务名称。请问是否存在相应接口，根据schemaId查询其所在微服务名的接口。谢谢！

**Comment by qizha** [comment]
schemaid在一个微服务里是唯一的，但是不同的微服务可以有一样的schema，所以现在还没有这样的接口。你是什么场景？为什么需要这样的接口的？

**Comment by zhengyangyong** [comment]
Hi @feelanture  , if you had any question, please contact us again, thanks!
