### ISSUE TITLE
多点击BMI Calculator报错

### ISSUE THREAD

**Issue by lorgine** [apache/incubator-servicecomb-java-chassis#238]
还有多运行几次后
Internal Server Error: com.netflix.zuul.exception.ZuulException

**Comment by eric-lee-ltk** [comment]
@lorgine 可以把详细的堆栈信息贴出来看看吗？

**Comment by soledad000** [comment]
我也是按照文档其服务后，只要点击就出现Internal Server Error: com.netflix.zuul.exception.ZuulException这个错

**Comment by kkrgwbj** [comment]
我这边没有发现问题.

**Comment by zhengyangyong** [comment]
@lorgine I think we may had fixed this issue by : https://github.com/apache/incubator-servicecomb-java-chassis/pull/658, you can try our latest version `1.0.0-m2`
