### ISSUE TITLE
按照QuickStart创建provider，报java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/FormatFeature

### ISSUE THREAD

**Issue by virtualf** [apache/incubator-servicecomb-java-chassis#277]

**Comment by virtualf** [comment]
maven依赖配置如下：
 。。。。
 <dependencies>
    <dependency>
      <groupId>io.servicecomb</groupId>
      <artifactId>spring-boot-starter-provider</artifactId>
      <version>0.4.1-SNAPSHOT</version>
    </dependency>
  </dependencies>
。。。。

**Comment by eric-lee-ltk** [comment]
在根模块中需要以pom的形式导入java chassis dependencies这个依赖项，可参考：https://github.com/ServiceComb/ServiceComb-Java-Chassis/blob/master/samples/bmi/pom.xml

**Comment by WillemJiang** [comment]
@virtualf 问题解决了吗？

**Comment by zhengyangyong** [comment]
Hi @virtualf  , if you had any question, please contact us again, thanks!
