### ISSUE TITLE
关于yaml文件版本号的问题

### ISSUE THREAD

**Issue by feelanture** [apache/incubator-servicecomb-java-chassis#279]
yaml文件微服务的version: 0.0.3，请问这个版本号如何使用？
比如两个点分隔的三个数字之间是什么关系？是最后的版本数字大小有一定限制吗，比如满1000进1，还是三个数字之间只是表示版本的级别？
另外，数字大小有限制吗，比如最后数字最大值可以是多少？

**Comment by liubao68** [comment]
版本号规则只是大家约定熟成的一个要求，三位也是参考了一般软件发布的规范。这块你们有特殊的应用场景吗？

**Comment by wujimin** [comment]
major.minor.patch
每个数字目前定义为正的short类型，没有其他原因，只是方便地做版本排序

**Comment by wujimin** [comment]
servicecomb本身没对这个做强制约束，默认要求新版本兼容旧版本
不过通过对版本号的规划，很容易达成major版本相同则兼容，minor表示新特性，patch表示patch fix的效果
配合consumer调用时设置的versionRule，可以路由到正确的目标实例

**Comment by zhengyangyong** [comment]
@feelanture if you have any question, please contact us
