### ISSUE TITLE
@RequestHeader获取不到Content-Length的值

### ISSUE THREAD

**Issue by zhoudong022** [apache/incubator-servicecomb-java-chassis#294]
@RequestHeader获取不到Content-Length的值

**Comment by WillemJiang** [comment]
请问客户传输方式是什么样的？ 看看能不能抓包看看是不是采用chuncked encoding的方式进行传输的。 
如果HTTP 传输是有Content-Length的话， 就是java-chassis的bug了。

**Comment by seanyinx** [comment]
现在通过HttpServletRequest.getParameter("Content-Length")可以获取，但@RequestHeader("Content-Length")获取不到，似乎是bug

**Comment by seanyinx** [comment]
not only content-length, sometimes the value of other headers may also be null when using @RequestHeader("header name").

the behavior seems to be random

**Comment by WillemJiang** [comment]
Let's create a JIRA track this issue,  it could easy for us to fix the issue by providing an test case.

**Comment by seanyinx** [comment]
https://servicecomb.atlassian.net/browse/JAV-542

**Comment by zhengyangyong** [comment]
Hi, @zhoudong022 ,this issues had resolved https://issues.apache.org/jira/browse/SCB-79, thanks!
