### ISSUE TITLE
啥时候支持流媒体数据传输啊？

### ISSUE THREAD

**Issue by zhousujian** [apache/incubator-servicecomb-java-chassis#298]
当前项目会用到图片、视频、音频相关流媒体数据，ServiceComb有计划支持吗？

**Comment by WillemJiang** [comment]
这个已经排到日程里面了，我们有个[JIRA](https://servicecomb.atlassian.net/browse/JAV-498)在跟踪这个任务。
能在这简单描述一下你使用场景吗？

**Comment by zhousujian** [comment]
我这边做无人机的，当前开发的系统是做无人机控制、监控、管理、运营一体化的云服务，正在切换ServiceComb框架，当前无人机会采集的视频，照片等流媒体数据进行后续分析计算，还有远程喊话的功能。具体场景：
1.视频直播，转储，下载等会对接第三方平台分析处理；
2.远程拍照到本地，大数据分析后生成报告等；
3.需要在控制中心喊话，发送给云端，再转发给无人机上的喊话设备进行喊话；
......

**Comment by lzk90s** [comment]
+1

**Comment by liubao68** [comment]
We have now provided download/upload features, please check PR https://github.com/apache/incubator-servicecomb-java-chassis/pull/690/files for examples.

**Comment by zhengyangyong** [comment]
@zhousujian Hi, we had support this feature, if have any question, please contact us again
