### ISSUE TITLE
error log has insufficient information when type not supported

### ISSUE THREAD

**Issue by seanyinx** [apache/incubator-servicecomb-java-chassis#301]
this error is thrown when a certain is not supported in controller
```
java.lang.Error: not support def type: class io.swagger.models.properties.BaseIntegerProperty
```

the type `BaseIntegerProperty` is not what user specified and the user specified type is not shown in log

**Comment by seanyinx** [comment]
related to https://github.com/ServiceComb/ServiceComb-Java-Chassis/issues/210

**Comment by zhengyangyong** [comment]
this [JIRA](https://issues.apache.org/jira/browse/SCB-76) had closed , if it occur again, we will reopen it
