### ISSUE TITLE
通过@RequestBody byte[] buffer接收字节时，为什么必须是json格式的才行

### ISSUE THREAD

**Issue by zhoudong022** [apache/incubator-servicecomb-java-chassis#304]
通过@RequestBody byte[] buffer接收字节时，若不是json格式，则直接报参数错误，为什么？

```
@RequestMapping(value = "/update", method = RequestMethod.PUT)
    public ResponseEntity<String> update(@PathVariable("accountId") Long accountId,
          @RequestHeader("Date") String date,
         @RequestBody byte[] buffer, HttpServletRequest request)
    {
           byte[] data = buffer;   //此处buffer必须是json格式
    }
```

**Comment by liubao68** [comment]
对于body类型的参数，缺省的Content-Type都是application/json（目前编码主要支持），所以都是json格式编码的byte[]数组。 如果需要上传、下载文件，参考示例：
https://github.com/apache/incubator-servicecomb-java-chassis/pull/690/files

**Comment by zhengyangyong** [comment]
+1,
Hi @zhoudong022 ,you can set request Content-Type as `text/plain` and  make a try
