### ISSUE TITLE
服务消费者的隔离信息是否可以通过API提供订阅发布能力，让外部感知到。

### ISSUE THREAD

**Issue by liushibin** [apache/incubator-servicecomb-java-chassis#338]
当前服务被隔离，一般是出现异常，内部虽然可以通过负载均衡冗余掉，但是还是需要有手段可获取到该信息，帮忙修复问题。

**Comment by WillemJiang** [comment]
不知道你提到的服务隔离指的是服务熔断，还是服务被调用之后出现问题被服务客户端识别之后从服务列表中删除？

**Comment by wujimin** [comment]
是达到指定失败率后被临时关小黑屋那个隔离

**Comment by wujimin** [comment]
这里要补充一下，隔离的是endpoint，不是实例，一个实例中可能有多个endpoint

**Comment by liushibin** [comment]
是的，这个没有问题。那个endpoint有问题就推送那个endpoint

**Comment by zhengyangyong** [comment]
Hi @liushibin  , if you had any question, please contact us again, thanks!
