### ISSUE TITLE
负载均衡使用问题

### ISSUE THREAD

**Issue by sniperLx** [apache/incubator-servicecomb-java-chassis#341]
我想使用负载均衡功能，按照官网的说明配置了pojo-consumer的microservice.yaml。以下是我实验的大致过程：

我启动多个pojo-provider实例在不同的端口，然后启动pojo-consumer，一切都正常。可是当我关掉一个pojo-provider实例时，pojo-consumer调用服务接口就失败了。

按我的理解，pojo-consumer在当前调用实例断开后，应该自动切换到另外一个pojo-provider实例上调用服务接口继续工作，然而实验结果并不是这样的。

请问我对ServiceComb负载均衡的理解是否有出错？

另外，能否增加microservice.yaml各配置项的使用说明。

非常感谢

**Comment by wujimin** [comment]
如果producer被直接强杀掉了，它没有机会向sc主动unregistered，那么只能等心跳超时后，sc才会将之标记为不可用，consumer才会将之从可用实例列表中清除

如果producer是正常退出，那么会向sc主动unregistered：
　1.如果是公有云，没有watch通道，只能等待下一个pull周期，取得新实例列表
　2.如果是云下，使用了watch功能，则sc会立即通知consumer实例列表更新
　但是，无论是哪个场景，哪怕通知再快，仍然还是会存在临界点，consumer仍然可能会使用坏掉的实例

consumer端的loadbalance：
　1.如果启用了重试（默认不启用），则在失败后会自动使用下一个实例重试
　2.如果启用了隔离（默认不启用），则在失败率达到配置值后，会自动将失败实例从可用列表中暂时移除，一段时间后，会拿出来重新放到可用列表中去

关于loadbalance的配置，请参考：[负载均衡策略](https://huawei-servicecomb.gitbooks.io/developerguide/content/build-provider/configuration/lb-strategy.html)

**Comment by zhengyangyong** [comment]
+1 to @wujimin 
Hi @sniperLx ,also we had support gracefully shutdown (https://github.com/apache/incubator-servicecomb-java-chassis/pull/693) in order to enhance it, if you have any question, please contact us again
