### ISSUE TITLE
ServiceComb是否有一个类似于JHipster这样包含完整的脚手架功能的微服务构建工具

### ISSUE THREAD

**Issue by zly2018** [apache/incubator-servicecomb-java-chassis#350]
ServiceComb是否有一个类似于JHipster这样包含完整的脚手架功能的微服务构建工具，
尤其是针对典型的应用场景，对企业应用开发用户来说透明，直接通过脚手架或者插件进行配置和构建，只要关注业务开发就好了。

**Comment by WillemJiang** [comment]
@zly2014 你的提议很好，目前我们做了一些帮助大家入门的例子，例如BMI， 或者复杂一些的Company，ServiceComb还没有提供类似JHipster的脚手架功能。 欢迎跟帖补充你最想要的业务场景，我们会不断丰富示例的同时提供脚手架功能。
