### ISSUE TITLE
schema有变化(除版本号+1)如何检测？

### ISSUE THREAD

**Issue by guocaifeng** [apache/incubator-servicecomb-java-chassis#351]
版本号不变的情况下，schema有变化，是否有监测变化的的这种接口或者监听器？    目前的方案是版本号加1，但是这种情况比较麻烦，而且管理起来不太方便，想找个替代方式解决这个问题。

**Comment by wujimin** [comment]
正在实施方案，开发态允许直接覆盖契约，不必修改版本号
不过如果有不兼容变化，consumer还是要根据新契约修改并重启的

在产品态，会增加契约的签名，启动时会与SC对比该契约的签名，如果发生变化，则认为有问题，中断启动流程。

**Comment by guocaifeng** [comment]
开发态如何进行直接覆盖契约操作呢？有对应的监听接口还是自动的？

**Comment by wujimin** [comment]
自动
开发者声明当前为开发态即可

**Comment by WillemJiang** [comment]
@wujimin 可以附上相关JIRA链接吗？ 这样可以让大家看到具体的进展状态。

**Comment by wujimin** [comment]
https://issues.apache.org/jira/browse/SCB-546

already finished.
