### ISSUE TITLE
启动时注册服务契约后，报关于Swagger的异常

### ISSUE THREAD

**Issue by gwj41** [apache/incubator-servicecomb-java-chassis#430]
定义的每个RestController都返回ResponseEntity<String>，例如
@RequestMapping(value = "/", method = RequestMethod.POST)
    public ResponseEntity<String> customerInfo(@RequestBody CustomerInfo customerInfo, HttpServletRequest request)
CustomerInfo.java
public class CustomerInfo {
    // 项目ID
    @JsonProperty(value = "PrecinctID",required = true)
    private Long precinctID;
    // 客户姓名
    @JsonProperty(value = "CustomerName",required = true)
    private String customerName;
    // 手机号码1
    @JsonProperty(value = "MobilePhone1",required = true)
    private String mobilePhone1;
    // 经纪人编号
    @JsonProperty(value = "BrokerID",required = true)
    private Long brokerID;
    // 经纪人姓名
    @JsonProperty(value = "BrokerName",required = true)
    private String brokerName;
    // 内部经纪人ID
    @JsonProperty(value = "ConsultantID",required = true)
    private Long consultantID;
    // 外部系统来源
    @JsonProperty(value = "SourceType",required = true)
    private Integer sourceType;
}
post:
      operationId: "customerInfo"
      parameters:
      - in: "body"
        name: "customerInfo"
        required: false
        schema:
          $ref: "#/definitions/data"
      responses:
        200:
          description: "response of 200"
          schema:
            type: "string"
其它几个接口的参数中也都没有引用到Object类型
异常信息如下
[ArrayIndexOutOfBoundsException.txt](https://github.com/ServiceComb/ServiceComb-Java-Chassis/files/1555349/ArrayIndexOutOfBoundsException.txt)

**Comment by seanyinx** [comment]
@gwj41 可以提供一下 `CustomerInfo` 类和生成的契约信息吗？

**Comment by wujimin** [comment]
所有成员变量都是私有的，且没有get/set方法  
所以CustomerInfo相当于没有成员变量

旧版本中对这种场景处理不完善，最新代码已经修复

**Comment by zhengyangyong** [comment]
Hello, @gwj41 , can you try the latest version of java chassis whether this issue still exist ?

**Comment by zhengyangyong** [comment]
Hi @gwj41  , if you had any question, please contact us again, thanks!
