### ISSUE TITLE
Optimization suggestions for README

### ISSUE THREAD

**Issue by MabinGo** [apache/incubator-servicecomb-java-chassis#469]
For the user to understand chassis quickly, it is better to added some more summary informations in README, eg.
1.Major features list
2.Summary design graph
3.Module dependency graph
4.Complete quick start guide
5.FAQ

What is your opinion?

**Comment by asifdxtreme** [comment]
+1

**Comment by zhangweixin** [comment]
+1

**Comment by WillemJiang** [comment]
@MabinGo
Please create a JIRA[1] in the for it. 
[1]https://issues.apache.org/jira/browse/SCB

**Comment by zhengyangyong** [comment]
Hi all , a lot of work has been done about this issue, thanks!
