### ISSUE TITLE
请问cse是否支持文件上传接口？之前内网版本实验着multipart是有问题的，谢谢

### ISSUE THREAD

**Issue by graphnj** [apache/incubator-servicecomb-java-chassis#559]

**Comment by WillemJiang** [comment]
你可以试一下最新的1.0.0-m1-SNAPSHOT,  访问地址是 https://repository.apache.org/content/repositories/snapshots/

**Comment by liubao68** [comment]
最新版本已经修复相关问题。 你问的是CSE版本，可以尝试2.3.8及其以上的版本, 参考：https://github.com/huawei-microservice-demo/huawei-microservice-demo

**Comment by graphnj** [comment]
2.3.8实验ok，谢谢
