### ISSUE TITLE
业务代码使用RegistryUtils方法报空指针

### ISSUE THREAD

**Issue by mt-monster** [apache/incubator-servicecomb-java-chassis#576]
业务代码在未使用BeanUtils启动框架时，直接通过RegistryUtils获取实例信息，因其内部serviceRegistry属性未做初始化，返回空指针。建议框架加内部保护，或者限定Bean的加载顺序，确保框架的Bean先于业务的Bean加载，避免此类问题。

**Comment by liubao68** [comment]
This is not a valid case. Make sure everything is ready before use it .

**Comment by zhengyangyong** [comment]
Hi,@mt-monster , you can use RegistryUtils after BootEvent of `AFTER_REGISTRY`, thanks

**Comment by mt-monster** [comment]
@liubao68  yep,i know it's not a very valid case, this scenery happened in some developer who don't really know about the SCB frame. issue just for follow the DTS , be better close it now
