### ISSUE TITLE
sample下面的bmi例子跑起来了，提交表单数据就报Internal Server Error: com.netflix.zuul.exception.ZuulException错误

### ISSUE THREAD

**Issue by soledad000** [apache/incubator-servicecomb-java-chassis#586]

**Comment by zhengyangyong** [comment]
can you provide more detail info ?

**Comment by zhengyangyong** [comment]
Hi @soledad000 ,can you provide more detail info such as exception trace ect..
You must start up service center first (http://servicecomb.incubator.apache.org/users/setup-environment/)

**Comment by zhengyangyong** [comment]
Hi @soledad000 , if you had any question, please contact us again, thanks!
