### ISSUE TITLE
【请关注】服务消费者调用服务提供者接口时，目前缺少接口级别或者动态的超时设置能力，无法满足服务接口差异化诉求

### ISSUE THREAD

**Issue by liushibin** [apache/incubator-servicecomb-java-chassis#592]
背景：升级过程中, 升级引擎与各服务交互都通过omprotal中转，采用rest方式通信．消息由升级引擎发送给omprotal，再由omportal转发到各服务进行处理．
　　　当前omprotal在转发消息后，默认的超时时间为30s，且该超时时间只支持客户端统一修改，即omprotal修改后，会导致所有经omprotal的请求超时时
　　　间都变为修改后的值，不满足多场景下的差异化诉求．
　　　
　　　升级场景下，调用的接口各服务可以自定义，前期出现过多起因为接口调用超时导致的失败问题：
（1）	接口设计时，预计处理时长十几秒，但是在超分环境下，超过30s，导致超时升级失败．
（2）	升级softwareMgr调用PaaS接口查询堆栈及DP信息，正常情况下5秒内返回，但是在PaaS侧处理繁忙时，可能会超过30S，导致升级界面超时失败．
　　　
　　　对于此类问题，升级侧以前尝试过以下三种方式，但都存在缺点：
（1）对于预期处理时间较长的接口，设计时设计为异步，即一个接口用于启动该处理，另一个接口用来查询该处理的状态，如果一两个接口的话，可以这样处理，
但是如果后续随着升级特性不断增加，此类接口会越来越多，开发成本相对就会越来越大．
（2）对于升级过程中调用的接口，如果定义为同步接口，要求无论何种场景下，都必须在30s内返回．但这种要求过于强制，达成效果无法保证．
（3）要求omprotal侧将默认的超时时间增长，但是增长到多少不好评估；且如果增长，对于其它场景也会有影响，比如WEB界面下发请求后，如果后台服务异常，
界面需要等待更长时间才能识别到超时，影响用户体验．

期望：
期望ServiceComb能够提供rest，rpc接口调用时的如下能力，以解决上述问题：
	服务端支持基于接口粒度的超时时间可配机制．
	支持客户端调用服务端接口时，接口超时时间可配机制．

**Comment by liubao68** [comment]
这个问题更像是一个复杂业务场景的解决方案。有些问题时需要深入讨论的。结合上面的描述，个人的一些建议：
1. 你给的三种尝试方案(1)/（2)是靠普的解决方案。期望的解决方案是不靠普的。获取好的用户体验，业务代码需要深入解决这两个方案碰到的问题。简单场景通常没问题，系统高负载或者资源少的情况下，还需要配合更加高级的一些措施，比如限流， 扩容等满足基本的服务质量。
2. 期望值为什么不靠普由几个建议： 服务端对于业务代码的超时是无法进行有效处理的（终止线程???），一般不存在超时的说法。客户端超时网络层的处理会增加检测成本，应用层使用hystrix组件之类的也可以做到，不过面对和服务端一样的问题，超时后的资源如何回收问题。

**Comment by qizha** [comment]
实际上你的要求是如何在微服务之间进行异步操作。命令-等候-查询结果的方式是其中的一种解决方案。而拉大调用的超时时间并不是好的方案，因为这个操作治标不治本，并不能根本解决你异步操作的问题，一旦异步的过程时间长了，就有问题了。
我推荐的方式是使用类似callback的方式，这个是REST的标准。可以参考OpenAPI的Specification:
https://swagger.io/specification/#callbackObject
也可以参考这个文章：https://dzone.com/articles/rest-callbacks

**Comment by zhengyangyong** [comment]
Hi @liushibin  , if you had any question, please contact us again, thanks!
