### ISSUE TITLE
Any example for using this micro-service framework without Spring?

### ISSUE THREAD

**Issue by lmsreborn** [apache/incubator-servicecomb-java-chassis#618]
Our company has been deploying all services based on Vert.x for a long time. I found that some transport modules in this framework is based on Vert.x. However, I didn't find any example for only using Vert.x without Spring. The example in **REST over Vertx**(http://servicecomb.incubator.apache.org/users/communicate-protocol/) seems depending on Spring as well. Would you please provide some examples without using Spring?

**Comment by liubao68** [comment]
Some of the core components use spring features, and most important part like Spring MVC programming feature. Thus java-chassis can not run without spring yet.

**Comment by zhengyangyong** [comment]
Hi @lmsreborn  , if you had any question, please contact us again, thanks!
