### ISSUE TITLE
java-chassis依赖的springboot版本过低

### ISSUE THREAD

**Issue by msnetc** [apache/incubator-servicecomb-java-chassis#654]
我们项目需要springboot版本是1.5.9， 而java-chassis的版本低于1.5.9， 是否能考虑升级到1.5.9。

**Comment by WillemJiang** [comment]
spring boot 1.5.x的最新版是1.5.12 （升级很快）， 我们会先验证1.5.x，应用本身还是需要能够重载spring boot的版本。

**Comment by liubao68** [comment]
java-chassis和spring boot的依赖关系是很松的，是作为它的一个组件使用。 应该你很容易使用spring boot的高版本集成和使用java-chassis。 说明参考：https://java.huaweicse.com/using-cse-in-spring-boot.html

**Comment by zhengyangyong** [comment]
https://github.com/apache/incubator-servicecomb-java-chassis/pull/673

**Comment by zhengyangyong** [comment]
PR merged,now java-chassis use 1.5.9 as default

**Comment by zhengyangyong** [comment]
Hi, @msnetc  ,we had upgrade spring boot to **15.12.RELEASE**, https://github.com/apache/incubator-servicecomb-java-chassis/pull/673, if you have any question, please contact us again
