### ISSUE TITLE
rpc模式下生成swagger-ui文档

### ISSUE THREAD

**Issue by msnetc** [apache/incubator-servicecomb-java-chassis#655]
bug:  rpc模式下，如果request 参数是complexttype， 甚至我直接声明一个简单对象，都不能生成swager-ui文档。
很多场合下，项目的请求参数有多个：如companyid，userid，token等。这样情况下如果一个方法传递多个参数，是一直用很不好的设计方式。
所以：我需要rpc模式下，request 参数如果是简单类型如（声明的java类中包含基本类型如int,string等）。可以生成swagger-ui文档。或者有没有别的替代方案。

**Comment by liubao68** [comment]
rpc模式下也是会生成契约的，契约可以在service-center查询，也会打印在日志中。 你说的swagger-ui和契约是什么关系？

**Comment by laijianbin** [comment]
swagger-ui应该是类似spring boot使用swagger提供了一个前台用来说明swagger。https://github.com/Yuicon/blog/issues/1

**Comment by zhengyangyong** [comment]
hi, we had improved in latest ServiceCenter, if have any question, please contact us again, thanks!
