### ISSUE TITLE
bmi项目的log日志没有输出

### ISSUE THREAD

**Issue by msnetc** [apache/incubator-servicecomb-java-chassis#656]
windows 机器：    <Property name="filePath">E:\dev\logs\</Property>
启动后，日志并没有输出

**Comment by zhengyangyong** [comment]
log4j2.xml in bmi is useless since 1.0.0-m1,you can create a JIRA and submit a PR remove(fix) it

**Comment by zhengyangyong** [comment]
Hi , we had add a sample ： https://github.com/apache/incubator-servicecomb-java-chassis/pull/735
