### ISSUE TITLE
是否考虑支持函数重载

### ISSUE THREAD

**Issue by keepongjl** [apache/incubator-servicecomb-java-chassis#659]
现在的Provider不支持函数重载（契约生成会报错Caused by: java.lang.Error: OperationId must be unique），是否考虑支持函数重载？

**Comment by liubao68** [comment]
目前是支持函数重载的， 加上@ApiOperation标签即可。每个接口必须有唯一的operation id

**Comment by zhengyangyong** [comment]
Hello, @keepongjl , you can see this example code : integration-tests\springmvc-tests\springmvc-tests-common\src\test\java\org\apache\servicecomb\demo\springmvc\tests\endpoints\CodeFirstSpringmvc.java , if you have any question, please contact us , thanks
