### ISSUE TITLE
怎样修改日志级别？

### ISSUE THREAD

**Issue by hank-whu** [apache/incubator-servicecomb-java-chassis#686]
参考 codefirst 修改 resources\config\log4j.demo.properties 看起来是不行的。

代码位置：https://github.com/hank-whu/rpc-benchmark/tree/master/servicecomb-server

**Comment by zhengyangyong** [comment]
I seems log configurations had loaded and processed, merged properties file can be found at : [main] INFO org.apache.servicecomb.foundation.common.utils.Log4jUtils - Write merged log4j config file to D:\WorkProject\rpc-benchmark\servicecomb-server\target\classes\config\merged.log4j.properties

In jdk8 is OK, we will looking for anything went wrong in jdk9.

**Comment by zhengyangyong** [comment]
Found is log implement issue , PR : https://github.com/hank-whu/rpc-benchmark/pull/14
