### ISSUE TITLE
Failed to define highway RPC

### ISSUE THREAD

**Issue by liguiz** [apache/incubator-servicecomb-java-chassis#716]
frontend 0.5 servicecomb 0.5
I define highway call using @RpcSchema(schemaId ="dict")
 and component-scan base-package.

but got:
```
2018-05-18 14:43:15,462 [WARN] Service does not exist. org.apache.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl.lambda$null$4(ServiceRegistryClientImpl.java:199)
2018-05-18 14:43:15,463 [ERROR] Can not find any instances from service center due to previous errors. service=default/CseMonitoring/latest org.apache.servicecomb.serviceregistry.registry.AbstractServiceRegistry.findServiceInstances(AbstractServiceRegistry.java:261)
```

I didn't define any client in the project.
use @RpcReference in comsumer project, got null.
And there is a hightway address in dashboard.but no client.

**Comment by zhengyangyong** [comment]
Hello,I think you can check whether instance had success registered in service center using frontend.
also you can check demo-pojo if any mistake.

use archetype generate a new pojo project may help you:
```bash
mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -DarchetypeGroupId=org.apache.servicecomb.archetypes -DarchetypeArtifactId=business-service-pojo-archetype -DarchetypeVersion=1.0.0-m2-SNAPSHOT -DarchetypeRepository=https://repository.apache.org/content/groups/snapshots-group
```

**Comment by wujimin** [comment]
are you using serviceComb or cse?
if it's cse, default will connect to monitor service, if can not find monitor, just print the logs, and will not cause any problem.

**Comment by liguiz** [comment]
Sorry for not fully checked, my client project scans the wrong package, so client wasn't initilized, which leads to fail rpc. It seems this log is printed by cse. Use servicecomb sdk install of cse paas, it disappears.
