### ISSUE TITLE
使用容器部署，注册中心获取到的是容器内的IP

### ISSUE THREAD

**Issue by highosimida** [apache/incubator-servicecomb-java-chassis#725]
如题，把微服务放入 docker 容器后，能在服务中心注册上， 但是注册的 endpoint 确是 docker 的内网网址如 highway://172.30.28.4:7070?login=true，而不是宿主机器的，如何注册成宿主机器的。

**Comment by liguiz** [comment]
[BMI Calculator Registry error in VM（分布式调用链跟踪）](https://github.com/apache/incubator-servicecomb-java-chassis/issues/154) this issue may help you.

**Comment by wujimin** [comment]
https://huaweicse.github.io/servicecomb-java-chassis-doc/zh_CN/build-provider/listen-address-and-publish-address.html

by "servicecomb.service.publishAddress" you can customize the publishAddress

**Comment by highosimida** [comment]
Thank you! Just what I want.

**Comment by jlynet** [comment]
容器不是一个资源池，

> 如题，把微服务放入 docker 容器后，能在服务中心注册上， 但是注册的 endpoint 确是 docker 的内网网址如 highway://172.30.28.4:7070?login=true，而不是宿主机器的，如何注册成宿主机器的。

@highosimida  你的问题解决了嘛？  我这边也遇到类似的问题了。容器平台厂家搞了两个容器资源池 搞到注册中心无法调用发布服务
