### ISSUE TITLE
Can't clone project as filename to long

### ISSUE THREAD

**Issue by fallblank** [apache/incubator-servicecomb-java-chassis#751]
Error occured when clone this project.

Cloning into 'D:\workspace\Github\incubator-servicecomb-java-chassis'...
POST git-upload-pack (800 bytes)
remote: Counting objects: 66134, done.
remote: Compressing objects: 100% (26/26), done.
Receiving objects: 100% (66134/66134), 11.02 MiB | 1.47 MiB/s, done.
Resolving deltas: 100% (25807/25807), done.
remote: Total 66134 (delta 5), reused 23 (delta 4), pack-reused 66100
Checking connectivity... done.

**error: unable to create file integration-tests/springmvc-tests/springmvc-tests-simplified-mapping-with-springboot/src/test/java/org/apache/servicecomb/demo/springmvc/tests/SpringMvcSpringSimplifiedMappingAnnotationIntegrationTest.java (Filename too long)**

Checking out files: 100% (2283/2283), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by WillemJiang** [comment]
It's a configuration issue on the window, you can find the solution here.
https://ourcodeworld.com/articles/read/109/how-to-solve-filename-too-long-error-in-git-powershell-and-github-application-for-windows

**Comment by fallblank** [comment]
Thanks, but SpringMvcSpringSimplifiedMappingAnnotationIntegrationTest.java smell bad, I think.
