### ISSUE TITLE
服务实例信息永远丢失

### ISSUE THREAD

**Issue by HancaiWang** [apache/incubator-servicecomb-java-chassis#796]
当如下代码块中microserviceInstance == null或needRefresh为false时，则服务实例如没有状态变化，则不会再更新服务实例信息，这样会导致暂时的同SC网络不稳定时，会引起返回结果不是200 OK，服务中服务实例信息与SC永远不一致  
public void pullInstances() {
    if (pendingPullCount.decrementAndGet() != 0) {
      return;
    }

    MicroserviceInstances microserviceInstances = RegistryUtils.findServiceInstances(appId,
        microserviceName,
        DefinitionConst.VERSION_RULE_ALL,
        revision);
    if (microserviceInstances == null) {
      return;
    }
    if (!microserviceInstances.isNeedRefresh()) {
      return;
    }
    List<MicroserviceInstance> pulledInstances = microserviceInstances.getInstancesResponse().getInstances();
    String rev = microserviceInstances.getRevision();

    safeSetInstances(pulledInstances, rev);
  }

**Comment by wujimin** [comment]
1.与SC失联，则保持当前缓存，避免业务中断  
  一旦与SC重新连接成功，则会重新获取数据，因为pull任务是定时执行的  
2.如果SC返回不必刷新，说明数据没有变化  
  
所以，没太明白，你说的永远丢失逻辑在哪里

**Comment by HancaiWang** [comment]
比如有2个SC（sc1,sc2），sc2故障了，而watch住sc1。
此时有服务实例A状态变化，但RegistryUtils.findServiceInstances则向SC2发消息，返回空。
当前场景下什么服务实例A的状态什么时候能再刷新为正确的状态呢？

**Comment by HancaiWang** [comment]
比如有2个SC（sc1,sc2），sc2故障了，而watch住sc1。
此时有服务实例A状态变化为上线（本地缓存为故障），但RegistryUtils.findServiceInstances则向SC2发消息，返回空。
当前场景下服务实例A的状态什么时候能再刷新为上线状态呢？

**Comment by wujimin** [comment]
sc1/sc2后面是同一个etcd集群  
一个sc实例故障，从另一个sc实例同样能取得正确结果的  
  
1.如果整个sc集群都连不上了，则sdk使用当前内存中的数据继续服务  
2.一旦能连上任意的sc实例，则会继续pull实例下来使用

**Comment by wujimin** [comment]
watch的作用是及时的触发pull  
而没有watch，也会定时去pull

**Comment by HancaiWang** [comment]
好好理解一下场景再回答，不懂不要乱回答。

关键是你pullInstances一次就不会再pullInstances了明白吗？后面再也不会pullInstances了，后面再也不会pullInstances了，后面再也不会pullInstances了；重要的事情说三遍，如果你还不理解，把问题带回去问问你们那儿技述好点的。
如下两个直接return是问题根因，你需要将其放到pullInstances失败列表中，要定其重新pullInstances去。
if (microserviceInstances == null) {
  return;
}
if (!microserviceInstances.isNeedRefresh()) {
  return;
}

**Comment by wujimin** [comment]
pullInstances是定时执行的  

1.RemoteServiceRegistry.run中启动定时任务，定时发起PeriodicPullEvent事件  
2.MicroserviceManager中订阅这个事件，起真正的pull操作

**Comment by zhengyangyong** [comment]
Hi @HancaiWang  , if you had any question, please contact us again, thanks!
