### ISSUE TITLE
你好,关于限流的一些疑问?

### ISSUE THREAD

**Issue by kkrgwbj** [apache/incubator-servicecomb-java-chassis#805]
servicecomb虽然提供了限流策略,但是感觉这个策略不太实用.实际业务中,一般都是基于用户+请求的具体url来做限流或者ip+url来做限流.servicecomb提供的是针对单一服务的.这就失去了很大的意义.

**Comment by WillemJiang** [comment]
针对用户和ip的限流可以在网关层面来设置，但是对于服务粒度的限流控制要通过网关来配置就不太好做了，目前java-chassis的针对服务级别的限流还是有场景的。

**Comment by wujimin** [comment]
for both consumer and producer, servicecomb support multiple level control:  
1.global  
2.service  
3.schema  
4.operation  

and for control by user/ip and so on, we will also add this feature
normally, this will be used in edge service

**Comment by kkrgwbj** [comment]
thanks.
