### ISSUE TITLE
通过脚手架创建的项目启动后,无法消费

### ISSUE THREAD

**Issue by kkrgwbj** [apache/incubator-servicecomb-java-chassis#808]
你好,用http://start.servicecomb.io/脚手架创建完项目,启动生产者项目后,成功注册到注册中心.但是我启动消费项目,消费报错
```
java.lang.IllegalStateException: System is not ready for remote calls. When beans are making remote calls in initialization, it's better to implement org.apache.servicecomb.core.BootListener and do it after EventType.AFTER_REGISTRY.

**Comment by kkrgwbj** [comment]
![image](https://user-images.githubusercontent.com/6836934/42743761-7716dbc0-88f9-11e8-95e1-cf4c54e7e833.png)

**Comment by kkrgwbj** [comment]
![image](https://user-images.githubusercontent.com/6836934/42744150-c063482e-88fc-11e8-910c-5acbf583093d.png)

**Comment by zhengyangyong** [comment]
I had test with 1.0.0-m2 and no problem, can you upgrade java chassis version ?
```xml
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.apache.servicecomb</groupId>
				<artifactId>java-chassis-dependencies</artifactId>
				<version>1.0.0-m2</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

**Comment by kkrgwbj** [comment]
升级为最新的,也是报了同样的错.

**Comment by zhengyangyong** [comment]
Here is my example,you can make a comparison ：
[demo.zip](https://github.com/apache/incubator-servicecomb-java-chassis/files/2199779/demo.zip)
