### ISSUE TITLE
sb版本还是1.5.x何时升级2.x

### ISSUE THREAD

**Issue by kkrgwbj** [apache/incubator-servicecomb-java-chassis#811]
sb版本还是1.5.x何时升级2.x

**Comment by kkrgwbj** [comment]
但是，springboot2.x最低要求spring核心库版本为5.x  但是，你们的组件很多底层依赖的spring核心版本是4.x，这就造成了问题。

**Comment by WillemJiang** [comment]
spring 5.x still support spring 4.x API. We don't need to do lots of change here.

**Comment by wujimin** [comment]
not so simple, we inject some logic to embedded servlet container, but parent class not exist any more
yaohaishi will post detail to dev mail list: https://mail.google.com/mail/#label/dev/164b281dcf290c5f
