### ISSUE TITLE
能否也提供一个Gradle的build脚本

### ISSUE THREAD

**Issue by wldandan** [apache/incubator-servicecomb-java-chassis#82]

**Comment by WillemJiang** [comment]
欢迎贡献一个gradle example ：）

**Comment by zhengyangyong** [comment]
We had added in these samples:
https://github.com/apache/incubator-servicecomb-java-chassis/tree/master/samples/bmi
https://github.com/apache/incubator-servicecomb-java-chassis/tree/master/samples/codefirst-sample
