### ISSUE TITLE
Is there any schedule to provide macOS version?

### ISSUE THREAD

**Issue by hjianhao** [apache/incubator-servicecomb-java-chassis#828]
Often use macOS for development, but service center only provide Windows and Linux version.

**Comment by WillemJiang** [comment]
ServiceCenter 1.0.0 MacOS version is voting now.  Please take a look at [this mail thread](https://lists.apache.org/thread.html/57e78cc996255fafc199a131653b96153331e855bf1beeee1982a389@%3Cdev.servicecomb.apache.org%3E).
You can find the release candidate [here](https://dist.apache.org/repos/dist/dev/incubator/servicecomb/incubator-servicecomb-service-center/1.0.0/rc-01/)

**Comment by zhengyangyong** [comment]
Hi @hjianhao  , if you had any question, please contact us again, thanks!
