### ISSUE TITLE
服务强制关闭,再打开的问题

### ISSUE THREAD

**Issue by kkrgwbj** [apache/incubator-servicecomb-java-chassis#829]
服务开启后如果我强制关闭,再打开一次  服务实例就会多一个..这是不是有问题?

**Comment by WillemJiang** [comment]
在服务中心心跳检查之前，服务中心是不知道实例下线了。 但是我们在客户端调用服务的过程中如果发现后台实例不能访问的话，客户端会把这个实例信息屏蔽掉的。

**Comment by kkrgwbj** [comment]
谢谢.
