### ISSUE TITLE
关于文件上传的疑问?

### ISSUE THREAD

**Issue by kkrgwbj** [apache/incubator-servicecomb-java-chassis#832]
为什么不支持这种请求?如果我其他参数非常多,要一个个定义吗?
```java
 @PostMapping(path = "/upload", consumes = MediaType.MULTIPART_FORM_DATA)
    public String fileUpload(UserVO userVO, MultipartFile file) {}
    public String fileUpload(UserVO userVO);

 public class UserVO{
 private String name;
private MultipartFile file;
}

**Comment by wujimin** [comment]
if all of your UserVO fields are query parameters, then in the latest code, we support this

but if not all of them are query parameters, then not support, because we can not generate correct contract.

**Comment by kkrgwbj** [comment]
期待你们最新的relaease

**Comment by wujimin** [comment]
in JaxRS development mode, @BeanParam is good way to IMPL this, but that's only for JaxRS

**Comment by kkrgwbj** [comment]
we use the springboot way .not use jaxrs

**Comment by wujimin** [comment]
it seems that there is no equals way in spring for @BeanParam, so currenly, only support query parameters in a bean.
